export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GET_SINGLE_MEAL_BEGIN = "GET_SINGLE_MEAL_BEGIN";
export const GET_SINGLE_MEAL_SUCCESS = "GET_SINGLE_MEAL_SUCCESS";
export const GET_SINGLE_MEAL_ERROR = "GET_SINGLE_MEAL_ERROR";
export const GET_MEALS_BEGIN = "GET_MEALS_BEGIN";
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";
export const GET_MEALS_ERROR = "GET_MEALS_ERROR";
