//meal context actions
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GET_SINGLE_MEAL_BEGIN = "GET_SINGLE_MEAL_BEGIN";
export const GET_SINGLE_MEAL_SUCCESS = "GET_SINGLE_MEAL_SUCCESS";
export const GET_SINGLE_MEAL_ERROR = "GET_SINGLE_MEAL_ERROR";
export const GET_MEALS_BEGIN = "GET_MEALS_BEGIN";
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";
export const GET_MEALS_ERROR = "GET_MEALS_ERROR";
//filter context actions
export const LOAD_MEALS = "LOAD_MEALS";
export const FILTER_MEALS = "FILTER_PRODUCTS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SORT_MEALS = "SORT_MEALS";
export const UPDATE_SORT = "UPDATE_SORT";
export const SET_LISTVIEW = "SET_LISTVIEW";
export const SET_GRIDVIEW = "SET_GRIDVIEW";
//cart context actions
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
//auth context actions
export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";